;Este programa consiste en la simulación de un cajero automatico
;Presentado por Ingrid Catherin Morales Correa y Alejandro Antonio Núñez Bonilla
;Códigos	201210207 			 201220574


p=16f887
#include    "p16f887.inc"
    
CBLOCK	0X20 
    NUMERO:4	    ;BANCO DE NUMEROS INGRESADOS POR TECLADO
    SALDO:3	    ;SALDO ACTUAL
    SALDO_TEMP:3    ;SALDO TEMPORAL PERMITE DETERMINAR SI EL RESULTADO ES CORRECTO Y EVENTUALMENTE (DEPENDIENDO DE SU
    ;CONSISTENCIA, ES DECIR, SI SE DETERMINA QUE EL RESULTADO ES CORRECTO) SE TRANSFERIRA A SALDO
    CONTRASENA:4    ;CONTRASEÑA	
    REST:3	    ;VALOR A RESTAR (Retiro)
    SALDO_AUX:3	    ;MUESTRA MODIFICABLE DE SALDO_AUX
    NUMERO_TEMPORAL ;VARIABLE AUXILIAR TEMPORAL DE TRABAJO
    FLAG	    ;0, IGUALDAD EN LA CONTRASEÑA;1, NO SE PUEDE HACER RETIRO;
		    ;2, COMPLETO EL INGRESO DE CARACTERES EN CAMB_CONTRASEÑA
    FLAG_ISR	    ;0, HAY CAMBIO EN TECLADO, NO O DATO IMPERCEPTIBLE; 1, DATO INGRESADO (CARACTERES); 2, B_ATRÁS
		    ;3, B_ENTER;4,  B_GOTO_INICIO; 5, BORRAR CARACTER
    TECLA	    ;VALOR TEMPORAL DE TECLA INGRESADA EN LA ISR
    S_TEMP	    ;REGISTRO PARA SALVADO DE CONTEXTO EN ISR
    W_TEMP	    ;REGISTRO PARA SALVADO DE CONTEXTO EN ISR
    m		    ;REGISTRO PARA RETARDO
    n		    ;REGISTRO PARA RETARDO
    o		    ;REGISTRO PARA RETARDO
    LCD_BUSSY_FLAG  ;REGISTRO QUE GUARDA LA LECTURA HECHA DE LA LCD
    I		    ;CONTADOR PARA MILISEGUNDOS 
    J		    ;VARIABLE CONTADORA EN LA LIBRERIA BANCO
    LIM_ESP	    ;PERMITA CAMBIAR EL TIEMPO DE ESPERA EN LA RUTINA ESPERA_Xms
    CONT_CONTRASENA ;CONTADOR DE CARRACTERES INGRESADOS DE LA CONTRASEÑA
    INTENTOS	    ;CANTIDAD DE INTENTOS QUE SE HA INGRESADO LA CONTRASEÑA
ENDC    

RES_VECT  CODE    0x0000            ; processor reset vector
  CALL	    OSC_CONF		    ;CONFIGURACION DEL OSCILADOR A 8Mhz
  CALL	    PORT_CONF		    ;CONFIGURACION DE PUERTOS
  CALL	    TECLADO_CONFIG	    ;CONFIGURA LOS REGISTROS NECESARIOS PARA CONECTAR UN TECLADO MATRICIAL EN PORTB
    GOTO    MAIN                   ; go to beginning of program

ISR_MAIN    CODE    0X04
    GOTO	ISR		    ;INTERRUPT VECTOR
    
MAIN_PROG   CODE	0X05                      ; let linker place main program
   MAIN:
   CALL		INI_VAR		    ;INICIALIZACIÓN DE TODAS LAS VARIABLES
   CALL		LCD_INIT	    ;INICIALIZA LA LCD PARA UN FUTURO USO
   REINICIO_PROG:
   BCF		INTCON, GIE	    ;DESHABILITA TODAS LAS INTERRUPCIONES
   CALL		M_BIENVENIDO	    ;CARGA EL MENSAJE DE BIENVENIDA
   CALL		RET5s		    ;ESPERA POR 5s CONE L MENSAJE DE BIENVENIDA
   MS:
   CLRF		FLAG_ISR	    
   CALL		M_MENU_PRINP	    ;CARGA EL MENSAJE DE MENU PRINCIPAL
   BSF		INTCON, GIE	    ;HABILITA LAS INTERRUPCIONES
   START:
   MOVLW	.150		    
   MOVWF	LIM_ESP
   CALL		ESPERA_Xms	    ;SE EJECUTA UN RETARDO DE 1.5s ANTES DE INICIAR EL DESPLAZAMIENTO
   MOVLW	.100
   MOVWF	LIM_ESP
   INI_DESPLAZAMIENTO:
   BTFSS	FLAG_ISR,0	;EVALUA SI HUBO UN CAMBIO VALIDO POR TECLADO PARA IR A LA OPERACIÓN
				;EN EL MENÚ DEL BANCO
	GOTO	DESPLAZAMIENTO
   GOTO		MENU_BANCO 	
   DESPLAZAMIENTO:
   CALL		SHIFT_SCREEN_D	;MUEVE EL SREEN DE LA PANTALLA
   CALL		ESPERA_Xms	;ESPERA DE 1 SEGUNDO ANTES DEL SIG CAMBIO EN LA SCREEN
   GOTO		INI_DESPLAZAMIENTO

    #include	"Retardos.inc"
    #include	"Configuracion.inc"
    #include	"M_LCD.inc"
    #include	"ISR.inc"
    #include	"BANCO.inc"
    
    END
